/**
 * Move Code Generators
 *
 * Generates Layer 1+2 (init_actions) and Layer 3 (execution) Move files
 * from action schemas.
 */

import {
  ActionSchema,
  CapBorrowDef,
  FieldDef,
  FieldRole,
  WrappedCallDef,
  MOVE_TYPE_MAP,
  normalizeRole,
  isResourceIn,
  isResourceOut,
  getInitModule,
  getActionStructName,
  getSpecFunctionName,
  getExecFunctionName,
  getFullMarkerType,
  getMarkerFactoryName,
  getPhantomTypes,
  packageToMoveAddr,
} from './parse-schema.js';

// =============================================================================
// LAYER 1 + 2: INIT ACTIONS (Action Struct + Spec Builder)
// =============================================================================

/**
 * Generate a complete *_init_actions.move file containing:
 * - Action struct (Layer 1)
 * - add_*_spec function (Layer 2)
 */
export function generateInitActions(schema: ActionSchema): string {
  const lines: string[] = [];
  const pkgAddr = packageToMoveAddr(schema.package);
  const initModule = getInitModule(schema);
  const structName = getActionStructName(schema);
  const specFn = getSpecFunctionName(schema);
  const phantomTypes = getPhantomTypes(schema);
  const typeParamsStr = buildSpecTypeParams(schema);
  const markerFactoryName = getMarkerFactoryName(schema);
  const markerFactoryCall = phantomTypes.length > 0
    ? `${pkgAddr}::${schema.module}::${markerFactoryName}<${phantomTypes.join(', ')}>()`
    : `${pkgAddr}::${schema.module}::${markerFactoryName}()`;

  // Header
  lines.push('// Copyright (c) Govex DAO LLC');
  lines.push('// SPDX-License-Identifier: BUSL-1.1');
  lines.push('');
  lines.push(`/// GENERATED by codegen — do not edit manually`);
  lines.push(`/// Init action staging for ${schema.name}`);
  lines.push(`module ${pkgAddr}::${initModule};`);
  lines.push('');

  // Imports
  lines.push('use account_protocol::intents;');
  const typesUsed = fieldTypesUsed(schema.fields);
  if (typesUsed.has('Option')) {
    lines.push('use std::option::Option;');
  }
  if (typesUsed.has('String')) {
    lines.push('use std::string::String;');
  }
  if (typesUsed.has('ID')) {
    lines.push('use sui::object::ID;');
  }
  lines.push('');

  // === Layer 1: Action Struct ===
  lines.push('// === Action Structs (for staging) ===');
  lines.push('');
  if (schema.description) {
    lines.push(`/// ${schema.description}`);
  }
  lines.push(`public struct ${structName} has copy, drop, store {`);
  for (const field of schema.fields) {
    const moveType = MOVE_TYPE_MAP[field.type].moveType;
    if (field.description) {
      lines.push(`    // ${field.description}`);
    }
    lines.push(`    ${field.name}: ${moveType},`);
  }
  lines.push('}');
  lines.push('');

  // === Layer 2: Spec Builder ===
  lines.push('// === Spec Builders (for PTB construction) ===');
  lines.push('');
  lines.push(`/// Add ${structName} to Builder`);
  lines.push(`/// Used for staging in proposals/launchpad via PTB`);

  // Function signature
  const specParams = buildSpecParams(schema);
  lines.push(`public fun ${specFn}${typeParamsStr}(`);
  lines.push('    builder: &mut account_actions::action_spec_builder::Builder,');
  for (const p of specParams) {
    lines.push(`    ${p},`);
  }
  lines.push(') {');

  // Function body
  lines.push('    use account_actions::action_spec_builder as builder_mod;');
  lines.push('    use sui::bcs;');
  lines.push('');

  // Create action struct
  lines.push(`    // Create action struct`);
  lines.push(`    let action = ${structName} {`);
  for (const field of schema.fields) {
    lines.push(`        ${field.name},`);
  }
  lines.push('    };');
  lines.push('');

  // Serialize
  lines.push('    // Serialize');
  lines.push('    let action_data = bcs::to_bytes(&action);');
  lines.push('');

  // Add to builder with marker type
  lines.push('    // Add to builder with marker type');
  lines.push(`    let action_spec = intents::new_action_spec(`);
  lines.push(`        ${markerFactoryCall},`);
  lines.push(`        action_data,`);
  lines.push(`        ${schema.version}, // version`);
  lines.push('    );');
  lines.push('    builder_mod::add(builder, action_spec);');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// =============================================================================
// LAYER 3: EXECUTION
// =============================================================================

/**
 * Generate a complete lib/<module>.move file containing:
 * - ExecutionProgressWitness struct
 * - Marker type struct + factory function
 * - do_init_* execution function (with TODO placeholder for custom logic)
 * - (no delete_* function needed — Expired has drop)
 */
export function generateExecution(schema: ActionSchema): string {
  const lines: string[] = [];
  const pkgAddr = packageToMoveAddr(schema.package);
  const phantomTypes = getPhantomTypes(schema);
  const execFn = getExecFunctionName(schema);
  const fullMarkerType = getFullMarkerType(schema);
  const exec = schema.execution;

  // Header
  lines.push('// Copyright (c) Govex DAO LLC');
  lines.push('// SPDX-License-Identifier: BUSL-1.1');
  lines.push('');
  lines.push(`/// GENERATED by codegen — do not edit manually`);
  lines.push(`/// Execution module for ${schema.name}`);
  lines.push(`module ${pkgAddr}::${schema.module};`);
  lines.push('');
  lines.push('public struct ExecutionProgressWitness has drop {}');
  lines.push('');
  lines.push('');

  // Imports
  lines.push('use account_protocol::action_validation;');
  lines.push('use account_protocol::bcs_validation;');
  lines.push('use account_protocol::executable::{Self, Executable};');
  lines.push('use account_protocol::intents;');

  if (exec.needsAccount) {
    lines.push('use account_protocol::account::{Self, Account};');
  }
  lines.push('use account_protocol::package_registry::PackageRegistry;');
  if (exec.capBorrow) {
    lines.push('use account_actions::access_control;');
  }

  const usesResources = schema.fields.some(
    (f) => isResourceIn(f.role) || isResourceOut(f.role),
  );
  if (usesResources) {
    lines.push('use account_protocol::executable_resources;');
  }

  // Standard imports based on field types
  const typesUsed = fieldTypesUsed(schema.fields);
  if (typesUsed.has('Option')) {
    lines.push('use std::option::{Self, Option};');
  }
  if (typesUsed.has('String')) {
    lines.push('use std::string::String;');
  }
  if (typesUsed.has('ID') || exec.externalObjects?.length) {
    lines.push('use sui::object::{Self, ID};');
  }
  lines.push('use sui::bcs;');
  if (exec.needsClock) {
    lines.push('use sui::clock::Clock;');
  }
  if (requiresCtx(schema)) {
    lines.push('use sui::tx_context::TxContext;');
  }

  lines.push('');

  // Errors
  lines.push('// === Errors ===');
  lines.push('');
  lines.push('const EUnsupportedActionVersion: u64 = 0;');
  if (exec.externalObjects?.length) {
    lines.push('const EExternalObjectMismatch: u64 = 1;');
  }
  lines.push('');

  // Marker type struct + factory
  lines.push('// === Action Type Markers ===');
  lines.push('');
  if (schema.description) {
    lines.push(`/// ${schema.description}`);
  }
  if (phantomTypes.length > 0) {
    const phantomParams = phantomTypes.map((t) => `phantom ${t}`).join(', ');
    lines.push(`public struct ${schema.marker.name}<${phantomParams}> has drop {}`);
    lines.push('');
    const factoryTypeParams = `<${phantomTypes.join(', ')}>`;
    const factoryName = getMarkerFactoryName(schema);
    lines.push(
      `public(package) fun ${factoryName}${factoryTypeParams}(): ${schema.marker.name}${factoryTypeParams} { ${schema.marker.name} {} }`,
    );
  } else {
    lines.push(`public struct ${schema.marker.name} has drop {}`);
    lines.push('');
    const factoryName = getMarkerFactoryName(schema);
    lines.push(
      `public(package) fun ${factoryName}(): ${schema.marker.name} { ${schema.marker.name} {} }`,
    );
  }
  lines.push('');

  // === Execution function ===
  lines.push('// === Public Functions ===');
  lines.push('');
  lines.push(`/// Execute ${schema.name} action`);

  // Build function signature
  const execTypeParams = buildExecTypeParams(schema);
  const execParams = buildExecParams(schema);

  lines.push(`public fun ${execFn}${execTypeParams}(`);
  for (const p of execParams) {
    lines.push(`    ${p},`);
  }
  lines.push(') {');

  // Function body: boilerplate
  if (exec.needsAccount) {
    lines.push(
      '    account::assert_execution_authorized(account, registry, executable, ExecutionProgressWitness {});',
    );
    lines.push('');
  }

  // Get ActionSpec
  lines.push('    // Get BCS bytes from ActionSpec');
  lines.push('    let specs = executable.intent().action_specs();');
  lines.push('    let action_spec = specs.borrow(executable.action_idx());');
  lines.push(`    action_validation::assert_action_type<${fullMarkerType}>(action_spec);`);
  lines.push('');

  // Get action data and version
  lines.push('    let action_data = intents::action_spec_data(action_spec);');
  lines.push('');
  lines.push('    // Check version before deserialization');
  lines.push('    let spec_version = intents::action_spec_version(action_spec);');
  lines.push(`    assert!(spec_version == ${schema.version}, EUnsupportedActionVersion);`);
  lines.push('');

  // BCS deserialization
  lines.push('    // Create BCS reader and deserialize');
  lines.push('    let mut reader = bcs::new(*action_data);');
  for (const field of schema.fields) {
    emitBcsPeel(lines, field);
  }
  lines.push('');

  // Validate all bytes consumed
  lines.push('    // Validate all bytes consumed');
  lines.push('    bcs_validation::validate_all_bytes_consumed(reader);');
  lines.push('');

  // Validate external object IDs
  if (exec.externalObjects?.length) {
    lines.push('    // Validate external object IDs match staged values');
    for (const obj of exec.externalObjects) {
      lines.push(
        `    assert!(object::id(${obj.name}) == ${obj.idField}, EExternalObjectMismatch);`,
      );
    }
    lines.push('');
  }

  // Take resources from executable_resources (resource_in_* fields)
  const resInFields = schema.fields.filter((f) => isResourceIn(f.role));
  if (resInFields.length > 0) {
    lines.push('    // Take resources from executable_resources');
    for (const field of resInFields) {
      const role = normalizeRole(field.role)!;
      const varName = resourceLocalName(field, role);
      const moveType = resourceMoveType(field, role, phantomTypes);
      if (role === 'resource_in_coin') {
        lines.push(`    let ${varName}: ${moveType} = executable_resources::take_coin(`);
        lines.push('        executable,');
        lines.push('        registry,');
        lines.push('        ExecutionProgressWitness {},');
        lines.push(`        ${field.name},`);
        lines.push('    );');
      } else if (role === 'resource_in_object') {
        lines.push(`    let ${varName}: ${moveType} = executable_resources::take_object(`);
        lines.push('        executable,');
        lines.push('        registry,');
        lines.push('        ExecutionProgressWitness {},');
        lines.push(`        ${field.name},`);
        lines.push('    );');
      }
    }
    lines.push('');
  }

  // Execution logic
  const resOutFields = schema.fields.filter((f) => isResourceOut(f.role));
  const hasReturn = resOutFields.length > 0;

  if (exec.capBorrow && schema.wrappedCall) {
    generateCapBorrowWithWrappedCall(lines, exec.capBorrow, schema.wrappedCall, hasReturn);
  } else if (exec.capBorrow) {
    generateCapBorrow(lines, exec.capBorrow);
    lines.push('');
    lines.push(
      '    // ========== EXECUTION LOGIC (HAND-WRITTEN) ==========',
    );
    lines.push(`    // Cap is available as "${exec.capBorrow.varName}" (passStyle: ${exec.capBorrow.passStyle})`);
    lines.push(
      '    // ====================================================',
    );
    lines.push('');
    generateCapReturn(lines, exec.capBorrow);
  } else if (schema.wrappedCall) {
    generateWrappedCall(lines, schema.wrappedCall, hasReturn);
  } else {
    lines.push(
      '    // ========== EXECUTION LOGIC (HAND-WRITTEN) ==========',
    );
    lines.push('    // TODO: Implement execution logic here');
    lines.push(
      '    // ====================================================',
    );
  }
  lines.push('');

  // Provide resources to executable_resources (resource_out_* fields)
  if (resOutFields.length > 0) {
    lines.push('    // Provide resources to executable_resources');
    for (const field of resOutFields) {
      const role = normalizeRole(field.role)!;
      // When wrappedCall is present, the call result var is `call_result`
      const resultVar = schema.wrappedCall ? 'call_result' : 'result_out';
      if (role === 'resource_out_coin') {
        lines.push(`    executable_resources::provide_coin(`);
        lines.push('        executable,');
        lines.push('        registry,');
        lines.push('        ExecutionProgressWitness {},');
        lines.push(`        ${field.name},`);
        lines.push(`        ${resultVar},`);
        lines.push('        ctx,');
        lines.push('    );');
      } else if (role === 'resource_out_object') {
        lines.push(`    executable_resources::provide_object(`);
        lines.push('        executable,');
        lines.push('        registry,');
        lines.push('        ExecutionProgressWitness {},');
        lines.push(`        ${field.name},`);
        lines.push(`        ${resultVar},`);
        lines.push('        ctx,');
        lines.push('    );');
      }
    }
    lines.push('');
  }

  // Increment action index
  lines.push(
    `    executable::increment_action_idx<_, ${fullMarkerType}, _>(executable, registry, ExecutionProgressWitness {});`,
  );
  lines.push('}');
  lines.push('');

  // No delete_* function needed — Expired has drop

  return lines.join('\n');
}

// =============================================================================
// HELPERS
// =============================================================================

/** Build parameter list for spec builder function */
function buildSpecParams(schema: ActionSchema): string[] {
  const params: string[] = [];
  for (const field of schema.fields) {
    const moveType = MOVE_TYPE_MAP[field.type].moveType;
    params.push(`${field.name}: ${moveType}`);
  }
  return params;
}

/** Build type params for the staging function. */
function buildSpecTypeParams(schema: ActionSchema): string {
  const phantoms = getPhantomTypes(schema);
  if (phantoms.length === 0) return '';
  const params = phantoms.map((phantom) => {
    const constraints = schema.execution.typeParamConstraints?.[phantom];
    return constraints && constraints.length > 0
      ? `${phantom}: ${constraints.join(' + ')}`
      : phantom;
  });
  return `<${params.join(', ')}>`;
}

/** Build type params string for execution function */
function buildExecTypeParams(schema: ActionSchema): string {
  const parts: string[] = [];
  const exec = schema.execution;

  // Config is needed when the function operates on Account-managed data (e.g. vaults)
  if (exec.needsAccount) {
    const constraints = exec.typeParamConstraints?.Config;
    parts.push(`Config: ${constraints && constraints.length > 0 ? constraints.join(' + ') : 'store'}`);
  }

  parts.push('Outcome: store');

  // Add phantom types from marker
  const phantoms = getPhantomTypes(schema);
  for (const phantom of phantoms) {
    if (exec.needsAccount && phantom === 'Config') continue;
    const constraints = exec.typeParamConstraints?.[phantom];
    if (constraints && constraints.length > 0) {
      parts.push(`${phantom}: ${constraints.join(' + ')}`);
    } else {
      parts.push(phantom);
    }
  }

  parts.push('IW: drop');

  return `<${parts.join(', ')}>`;
}

/** Build parameter list for execution function */
function buildExecParams(schema: ActionSchema): string[] {
  const params: string[] = [];
  const exec = schema.execution;

  params.push('executable: &mut Executable<Outcome>');

  if (exec.needsAccount) {
    params.push('account: &mut Account');
  }
  params.push('registry: &PackageRegistry');

  // External objects
  if (exec.externalObjects) {
    for (const obj of exec.externalObjects) {
      const mutPrefix = obj.mutable ? '&mut ' : '&';
      params.push(`${obj.name}: ${mutPrefix}${obj.type}`);
    }
  }

  if (exec.needsClock) {
    params.push('clock: &Clock');
  }

  params.push('_intent_witness: IW');

  if (requiresCtx(schema)) {
    params.push('ctx: &mut TxContext');
  }

  return params;
}

/** Emit a BCS peel block for a field. */
function emitBcsPeel(lines: string[], field: FieldDef): void {
  const mapping = MOVE_TYPE_MAP[field.type];
  if (mapping.bcsPeel.startsWith('OPTION_')) {
    const innerType = field.type.replace('Option<', '').replace('>', '');
    const innerPeel = getInnerOptionPeel(innerType);
    lines.push(`    let ${field.name} = if (bcs::peel_bool(&mut reader)) {`);
    lines.push(`        option::some(${innerPeel})`);
    lines.push('    } else {');
    lines.push('        option::none()');
    lines.push('    };');
    return;
  }

  if (field.type === 'vector<String>') {
    lines.push(`    let ${field.name}_len = bcs::peel_vec_length(&mut reader);`);
    lines.push(`    let mut ${field.name} = vector::empty<String>();`);
    lines.push(`    let mut ${field.name}_i = 0;`);
    lines.push(`    while (${field.name}_i < ${field.name}_len) {`);
    lines.push(`        ${field.name}.push_back(std::string::utf8(bcs::peel_vec_u8(&mut reader)));`);
    lines.push(`        ${field.name}_i = ${field.name}_i + 1;`);
    lines.push('    };');
    return;
  }

  if (field.type === 'vector<address>') {
    lines.push(`    let ${field.name}_len = bcs::peel_vec_length(&mut reader);`);
    lines.push(`    let mut ${field.name} = vector::empty<address>();`);
    lines.push(`    let mut ${field.name}_i = 0;`);
    lines.push(`    while (${field.name}_i < ${field.name}_len) {`);
    lines.push(`        ${field.name}.push_back(bcs::peel_address(&mut reader));`);
    lines.push(`        ${field.name}_i = ${field.name}_i + 1;`);
    lines.push('    };');
    return;
  }

  lines.push(`    let ${field.name} = ${mapping.bcsPeel};`);
}

/** Get inner BCS peel expression for Option types */
function getInnerOptionPeel(innerType: string): string {
  switch (innerType) {
    case 'u64':
      return 'bcs::peel_u64(&mut reader)';
    case 'u128':
      return 'bcs::peel_u128(&mut reader)';
    case 'bool':
      return 'bcs::peel_bool(&mut reader)';
    case 'String':
      return 'std::string::utf8(bcs::peel_vec_u8(&mut reader))';
    default:
      return `/* TODO: peel ${innerType} */`;
  }
}

/** Collect which field types are used */
function fieldTypesUsed(fields: FieldDef[]): Set<string> {
  const used = new Set<string>();
  for (const f of fields) {
    if (f.type.startsWith('Option<')) {
      used.add('Option');
    }
    if (f.type === 'String' || f.type === 'Option<String>' || f.type === 'vector<String>') {
      used.add('String');
    }
    if (f.type === 'ID') {
      used.add('ID');
    }
  }
  return used;
}

function requiresCtx(schema: ActionSchema): boolean {
  return Boolean(schema.execution.needsCtx || schema.fields.some((f) => isResourceOut(f.role)));
}

function resourceLocalName(field: FieldDef, role: FieldRole): string {
  if (field.resourceVarName) return field.resourceVarName;
  if (field.name.endsWith('_resource')) return field.name.replace(/_resource$/, '');
  if (field.name.endsWith('_resource_name')) return field.name.replace(/_resource_name$/, '');
  if (field.name === 'resource_name') {
    return role === 'resource_in_object' ? 'object' : 'coin';
  }
  return `${field.name}_resource`;
}

function resourceMoveType(field: FieldDef, role: FieldRole, phantomTypes: string[]): string {
  if (field.moveType) {
    return role === 'resource_in_coin' || role === 'resource_out_coin'
      ? canonicalCoinType(field.moveType)
      : field.moveType;
  }

  const fallbackType = phantomTypes.length > 0 ? phantomTypes[0] : 'CoinType';
  return role === 'resource_in_coin' || role === 'resource_out_coin'
    ? `sui::coin::Coin<${fallbackType}>`
    : fallbackType;
}

function canonicalCoinType(moveType: string): string {
  const trimmed = moveType.trim();
  const coinMatch = trimmed.match(/^(?:sui::)?(?:coin::)?Coin<(.+)>$/);
  if (!coinMatch) return trimmed;
  return `sui::coin::Coin<${coinMatch[1].trim()}>`;
}

/** Generate the actual wrapped function call for Layer 3 */
function generateWrappedCall(lines: string[], call: WrappedCallDef, hasReturn: boolean): void {
  lines.push(`    // Call wrapped function: ${call.target}`);

  const typeParamsStr = call.typeParams.length > 0
    ? `<${call.typeParams.join(', ')}>`
    : '';

  const argStrs = call.args.map((arg) => arg.varName);

  const callExpr = `${call.target}${typeParamsStr}`;

  if (argStrs.length <= 3) {
    const argsInline = argStrs.join(', ');
    if (hasReturn) {
      lines.push(`    let call_result = ${callExpr}(${argsInline});`);
    } else {
      lines.push(`    ${callExpr}(${argsInline});`);
    }
  } else {
    if (hasReturn) {
      lines.push(`    let call_result = ${callExpr}(`);
    } else {
      lines.push(`    ${callExpr}(`);
    }
    for (let i = 0; i < argStrs.length; i++) {
      const comma = i < argStrs.length - 1 ? ',' : ',';
      lines.push(`        ${argStrs[i]}${comma}`);
    }
    lines.push('    );');
  }
}

/** Emit the remove_managed_asset call to borrow a cap from the Account */
function generateCapBorrow(lines: string[], cap: CapBorrowDef): void {
  lines.push('    // Borrow cap internally from account');
  const mutPrefix = cap.passStyle === 'mut_ref' ? 'mut ' : '';
  lines.push(`    let (${mutPrefix}${cap.varName}, ${cap.varName}_receipt) = access_control::remove_cap<Outcome, ${cap.capType}, _>(`);
  lines.push('        account,');
  lines.push('        registry,');
  lines.push('        executable,');
  lines.push('        ExecutionProgressWitness {},');
  lines.push('    );');
}

/** Emit the add_managed_asset call to return a cap to the Account */
function generateCapReturn(lines: string[], cap: CapBorrowDef): void {
  lines.push('    // Return cap to account');
  lines.push(`    access_control::return_cap<Outcome, ${cap.capType}, _>(`);
  lines.push('        account,');
  lines.push('        registry,');
  lines.push(`        ${cap.varName},`);
  lines.push(`        ${cap.varName}_receipt,`);
  lines.push('        executable,');
  lines.push('        ExecutionProgressWitness {},');
  lines.push('    );');
}

/** Emit borrow → wrapped call (with passStyle handling) → return */
function generateCapBorrowWithWrappedCall(
  lines: string[],
  cap: CapBorrowDef,
  call: WrappedCallDef,
  hasReturn: boolean,
): void {
  // Borrow cap
  generateCapBorrow(lines, cap);
  lines.push('');

  // Build arg strings, rendering cap_borrow args according to passStyle
  const typeParamsStr = call.typeParams.length > 0
    ? `<${call.typeParams.join(', ')}>`
    : '';

  const argStrs = call.args.map((arg) => {
    if (arg.source === 'cap_borrow') {
      switch (cap.passStyle) {
        case 'ref': return `&${cap.varName}`;
        case 'mut_ref': return `&mut ${cap.varName}`;
        default: return cap.varName;
      }
    }
    return arg.varName;
  });

  const callExpr = `${call.target}${typeParamsStr}`;

  // For value passStyle, the call returns the cap — need reassignment
  const needsCapReassign = cap.passStyle === 'value';
  // For value + resource_out, we'd need tuple destructuring — emit TODO
  const hasResourceOut = hasReturn;

  if (needsCapReassign && hasResourceOut) {
    lines.push('    // TODO: value passStyle + resource_out requires tuple destructuring');
  }

  lines.push(`    // Call wrapped function: ${call.target}`);

  // Determine what the call assigns to
  let assignPrefix = '';
  if (needsCapReassign && hasResourceOut) {
    // Rare: tuple destructuring needed
    assignPrefix = `let (${cap.varName}, call_result) = `;
  } else if (needsCapReassign) {
    assignPrefix = `let ${cap.varName} = `;
  } else if (hasResourceOut) {
    assignPrefix = 'let call_result = ';
  }

  if (argStrs.length <= 3) {
    const argsInline = argStrs.join(', ');
    lines.push(`    ${assignPrefix}${callExpr}(${argsInline});`);
  } else {
    lines.push(`    ${assignPrefix}${callExpr}(`);
    for (let i = 0; i < argStrs.length; i++) {
      const comma = i < argStrs.length - 1 ? ',' : ',';
      lines.push(`        ${argStrs[i]}${comma}`);
    }
    lines.push('    );');
  }

  lines.push('');

  // Return cap
  generateCapReturn(lines, cap);
}
